name: Validate DAB Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Databricks CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
    - name: Validate bundle
      # TODO: Add the validate command
      # Follow the instructions in the README to install the CLI and run the validate command
      # https://github.com/databricks/setup-cli?tab=readme-ov-file#github-actions
      run: |
        echo "databricks bundle validate"
